services:
  - type: web
    name: nice-shopping
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_PASS
        value: admin2025
    pullRequestPreviewsEnabled: false
